### ISSUE TITLE
您好，麻烦写一个用法的readme吧！

### ISSUE THREAD

**Issue by Lawrenceeeeeeeeee** [ggchivalrous/yiyin#1]
我下载了win32的，但是用不了，选择照片和输出目录之后，点击生成水印没有生成，也没有其他报错。

**Comment by ggchivalrous** [comment]
有截图看看嘛，readme我后面补上

**Comment by ggchivalrous** [comment]
> 我下载了win32的，但是用不了，选择照片和输出目录之后，点击生成水印没有生成，也没有其他报错。
有截图看看嘛，readme我后面补上

**Comment by ggchivalrous** [comment]
有截图看看嘛，readme我后面补上

**Comment by ggchivalrous** [comment]
<img width="550" alt="image" src="https://github.com/ggchivalrous/yiyin/assets/76425888/1644e7e0-a9ec-4c47-bca1-cfece5d9a18b">
正常点击这个地方打开输出目录就能看到生成的图片，图片生成可能没那么快。报错的话，我没怎么输出所以可能看不到

**Comment by Lawrenceeeeeeeeee** [comment]
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/e034ee81-0b74-483f-b04f-3996e2b100c3)、
这是还没输出
![Uploading image.png…]()
这是点击生成以后，但是桌面并没有出现照片。所以我的疑问是我是不是有什么步骤出错了

**Comment by ggchivalrous** [comment]
你图片是不是在桌面呀，输出的图片名字不变的，会直接覆盖的

**Comment by Lawrenceeeeeeeeee** [comment]
可是我选择不在桌面的图片生成水印输出到桌面，但是也没有输出。

**Comment by Lawrenceeeeeeeeee** [comment]
您看您能不能发一个实例啥的，还有我用的系统是win11

**Comment by ggchivalrous** [comment]
![image](https://github.com/ggchivalrous/yiyin/assets/76425888/b678d59b-b03a-404a-a553-c82c7534d89f)
你点一下这个文字，看看打开的目录里面有没有

**Comment by Lawrenceeeeeeeeee** [comment]
还是不行。
1. 
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/a7d2a51c-f0ea-4a84-bbeb-b7fc856374d4)
以上是我选择的桌面图片，输出目录是桌面的album。

2. 
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/ff6802c3-831a-4f52-a1c3-11a05d09e554)
然而打开文件夹并没有任何东西

**Comment by ggchivalrous** [comment]
<img width="549" alt="image" src="https://github.com/ggchivalrous/yiyin/assets/76425888/e80879f6-135e-4cb1-965b-8dd0f658211c">
<img width="910" alt="image" src="https://github.com/ggchivalrous/yiyin/assets/76425888/122a9f97-6484-4191-a491-3515ff7e2447">
<img width="920" alt="image" src="https://github.com/ggchivalrous/yiyin/assets/76425888/b10c2ec6-b4a3-44d3-ae8a-f4beea8abba7">
我用虚拟机win11，试了一下，有正常输出

**Comment by Lawrenceeeeeeeeee** [comment]
你是mac开发的吗？虚拟机的话我不知道，但是我win11确实不行，我刚才还下载另一个版本，但是打开好像是mac版本的，并不是win。

**Comment by ggchivalrous** [comment]
还有一种可能，你的图片不是相机图片，在读取相机信息那块可能出错了，因为我用截图的图片试了一下，输出不了

**Comment by Lawrenceeeeeeeeee** [comment]
那我试试相机拍的

**Comment by Lawrenceeeeeeeeee** [comment]
还真是！！！

**Comment by ggchivalrous** [comment]
哈哈哈，应该就是读取相机信息那里报错了，我catch了，防止程序崩溃

**Comment by Lawrenceeeeeeeeee** [comment]
不过好像还是有问题，同一个相机拍的，另一张也生成不了。

**Comment by Lawrenceeeeeeeeee** [comment]
不纠结这个问题了，那我如果想修改成像比例怎么做呢，就是背景我希望能够统一铺满16：9的全屏。

**Comment by ggchivalrous** [comment]
这个现在不支持，背景是使用原图大小做的，除非你的图片就是16:9的

**Comment by ggchivalrous** [comment]
我这个目前就只有生成印框的功能，如果需要这种修改比例的，后面我看看能不能做出来

**Comment by Lawrenceeeeeeeeee** [comment]
但是竖图生成的好像也是一个类似3：2的比例呀

**Comment by ggchivalrous** [comment]
有个横屏输出的功能

**Comment by ggchivalrous** [comment]
背景是横屏的，然后图片竖直放在中间

**Comment by Lawrenceeeeeeeeee** [comment]
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/01a2f8a3-eb99-482f-a0a7-d7b0e94401a4)
我查看你以下这个代码，不知道修改这里行不行。

**Comment by Lawrenceeeeeeeeee** [comment]
这里好像就是规定背景的比例的？

**Comment by ggchivalrous** [comment]
这里是缩放比例，这个是我测试的图片大小，然后根据比例转成实际图片的大小所要的虚化和圆角而已

**Comment by ggchivalrous** [comment]
实际输出要在程序里面改，这个是页面端的

**Comment by Lawrenceeeeeeeeee** [comment]
你整个源码几乎是前端的语言，所以我都不太懂。

**Comment by ggchivalrous** [comment]
整套都是javascript的，我对这个比较熟

**Comment by Lawrenceeeeeeeeee** [comment]
是的，我是希望不论什么比例的图片，生成的都是铺满全屏的背景，不然有点强迫，也不协调。

![image](https://github.com/ggchivalrous/yiyin/assets/76642508/c03ece8c-bd12-45cb-ad14-602a7767e3bd)
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/5b1f0f98-8ba8-4411-8d57-3d1756eb443e)
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/29ba5d94-440f-4f5c-9201-b5ec8d3c4d84)
你看这三种不同比例的图片，既不能统一背景的比例，很难受。希望可以改进一下

**Comment by ggchivalrous** [comment]
可以，我给你记下来(⁎⁍̴̛ᴗ⁍̴̛⁎)

**Comment by Lawrenceeeeeeeeee** [comment]
感谢！期待您的新的release!
