### ISSUE TITLE
v1.30 macos 测试无效，无输出文件，1.21 正常

### ISSUE THREAD

**Issue by hnsxxscyx** [ggchivalrous/yiyin#10]
macos 14.1.1
mbp 14
以给full disk 权限。不给权限前也未对download / document 等文件夹索要权限。
但我猜想与环境无关，我简单看了下代码，但是没跑环境，没看出来啥特别的。
建议增加log 记录输出？

**Comment by hnsxxscyx** [comment]
> 我也遇到了，你试试卸了重装

我是第一次安装1.3 版本～

**Comment by ggchivalrous** [comment]
日志这个我在弄，我本地跑起来他就立马又可以了

**Comment by ggchivalrous** [comment]
我要去重现一下，感觉是哪里出了问题

**Comment by hnsxxscyx** [comment]
electron 可以直接用window.api.startTask 这个吗？我不太熟悉这个，我搜了下一般是用ipcMain 来触发和监听的？

**Comment by ggchivalrous** [comment]
是用的ipcMain，那是在main里面注册用的，在前端页面用一个指定的对象来调用暴露出来的函数和electron通信的

**Comment by ggchivalrous** [comment]
这个api在preload里面暴露出去的

**Comment by hnsxxscyx** [comment]
ok，明天我有空的话而且没找到原因的话我也调一下

**Comment by ggchivalrous** [comment]
好像还有几个问题哈哈，有些样式没生效，跟我调试的效果不一样(/ω＼)

**Comment by Zekakora** [comment]
Windows v1.3.1输出也没有文件

**Comment by ggchivalrous** [comment]
@Zekakora 卸了重装也这样吗

**Comment by ggchivalrous** [comment]
问题排查出来了，缓存目录忘记创建了，导致文件操作异常

**Comment by ggchivalrous** [comment]
问题在1.3.3中修复
