### ISSUE TITLE
Mac mini M1 适配有问题

### ISSUE THREAD

**Issue by erbiaoger** [ggchivalrous/yiyin#16]
Mac mini M1 使用可以获得相机信息，但是无法写入，导不成新的图片。

**Comment by ggchivalrous** [comment]
用的什么版本

**Comment by ggchivalrous** [comment]
有人反馈无人机的照片输出有问题，用相机的就没事

**Comment by erbiaoger** [comment]
14.1.1

**Comment by erbiaoger** [comment]
我在windows也试了，发现可能是图片的原因。windows也不行。

**Comment by erbiaoger** [comment]
{
  "Make": "Apple",
  "Model": "iPhone 11",
  "Orientation": 1,
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "Software": "16.6",
  "ModifyDate": 1691587967,
  "HostComputer": "iPhone 11",
  "YCbCrPositioning": 1,
  "GPSLatitudeRef": "N",
  "GPSLatitude": 43.877769444444446,
  "GPSLongitudeRef": "E",
  "GPSLongitude": 125.29946944444444,
  "GPSAltitudeRef": 0,
  "GPSAltitude": 232.7767690875233,
  "GPSTimeStamp": [
    20,
    0,
    0
  ],
  "GPSSpeedRef": "K",
  "GPSSpeed": 0.35113866255869636,
  "GPSImgDirectionRef": "T",
  "GPSImgDirection": 42.8296814087915,
  "GPSDestBearingRef": "T",
  "GPSDestBearing": 42.8296814087915,
  "GPSDateStamp": "2023:08:09",
  "GPSHPositioningError": 14.25028735632184,
  "ExposureTime": 0.00021701388888888888,
  "FNumber": 1.8,
  "ExposureProgram": 2,
  "ISO": 32,
  "DateTimeOriginal": 1691587967,
  "CreateDate": 1691587967,
  "undefined": "+08:00",
  "ShutterSpeedValue": 12.17001733102253,
  "ApertureValue": 1.6959938128383605,
  "BrightnessValue": 10.60299021189631,
  "ExposureCompensation": 0,
  "MeteringMode": 5,
  "Flash": 16,
  "FocalLength": 4.25,
  "SubjectArea": [
    2006,
    1501,
    2309,
    1383
  ],
  "SubSecTimeOriginal": "670",
  "SubSecTimeDigitized": "670",
  "ColorSpace": 65535,
  "ExifImageWidth": 4032,
  "ExifImageHeight": 3024,
  "SensingMethod": 2,
  "ExposureMode": 0,
  "WhiteBalance": 0,
  "DigitalZoomRatio": 1.5444330949948928,
  "FocalLengthIn35mmFormat": 40,
  "SceneCaptureType": 0,
  "LensInfo": [
    1.5399999618512084,
    4.25,
    1.8,
    2.4
  ],
  "LensMake": "Apple",
  "LensModel": "iPhone 11 back dual wide camera 4.25mm f/1.8"
}

这是相机信息。但图片相框导不出来。

**Comment by ggchivalrous** [comment]
嗯，我现在怀疑是信息图片不是jpeg 图片，所以在生成背景图时异常了

**Comment by erbiaoger** [comment]
{
  "ImageWidth": 4000,
  "ImageHeight": 2252,
  "Make": "samsung",
  "Model": "Pixel",
  "Orientation": 1,
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "Software": "G9880ZCU3GVK4",
  "ModifyDate": 1680283561,
  "YCbCrPositioning": 1,
  "GPSLatitudeRef": "N",
  "GPSLatitude": 43.883456,
  "GPSLongitudeRef": "E",
  "GPSLongitude": 125.2981376,
  "ExposureTime": 0.01,
  "FNumber": 1.8,
  "ExposureProgram": 2,
  "ISO": 40,
  "DateTimeOriginal": 1680283561,
  "CreateDate": 1680283561,
  "undefined": "+08:00",
  "ShutterSpeedValue": 0.01,
  "ApertureValue": 1.69,
  "BrightnessValue": 4.64,
  "ExposureCompensation": 0,
  "MaxApertureValue": 1.69,
  "MeteringMode": 3,
  "Flash": 0,
  "FocalLength": 7,
  "SubSecTime": "0062",
  "SubSecTimeOriginal": "0062",
  "SubSecTimeDigitized": "0062",
  "ColorSpace": 1,
  "ExifImageWidth": 4000,
  "ExifImageHeight": 2252,
  "ExposureMode": 0,
  "WhiteBalance": 0,
  "DigitalZoomRatio": 1,
  "FocalLengthIn35mmFormat": 25,
  "SceneCaptureType": 0,
  "ImageUniqueID": "SA8XLMF01SM"
}
三星，苹果，oppo，都是。

**Comment by erbiaoger** [comment]
三星和oppo是jpeg格式。

**Comment by ggchivalrous** [comment]
#6 这个issues 里面有相机的图片，你试试

**Comment by erbiaoger** [comment]
{
  "Orientation": 1,
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": 2,
  "YCbCrPositioning": 1,
  "ColorSpace": 1,
  "ExifImageWidth": 1080,
  "ExifImageHeight": 1920,
  "SceneCaptureType": 0
}
但现在有几张jpg图片，相机信息是这样的。可以导出，但没有相机型号等等。

**Comment by erbiaoger** [comment]
好，我来试试。

**Comment by ggchivalrous** [comment]
我觉得是ffmpeg 模块的问题，有些图片不用识别，直接异常

**Comment by erbiaoger** [comment]
[1](https://private-user-images.githubusercontent.com/69229029/285255780-79cefbc5-bd2b-45f0-8b88-b015703d162f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTU0NDIsIm5iZiI6MTcwMTE1NTE0MiwicGF0aCI6Ii82OTIyOTAyOS8yODUyNTU3ODAtNzljZWZiYzUtYmQyYi00NWYwLThiODgtYjAxNTcwM2QxNjJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzQ4Yjg1ZTdiZjkyZDk1ZjdmMGNlZjc5YmQ1N2M0MjMxYTZiZWQ5OTdhNzJmYTA5YTgxZWYyNWI0ZWJhZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iJh2tuudIjuyKWt66fF4xxOeP2BGchrvo9xZgDHBzHM)这里的照片没有问题，mac上也可以正常导出

**Comment by erbiaoger** [comment]
有可能了，相机照片和手机照片，的区别了

**Comment by ggchivalrous** [comment]
应该不是，ffmpeg 好像只能识别jpeg 的图片，我看日志输出的错误信息推测的，所以我只要加一层转换就行了

**Comment by erbiaoger** [comment]
好，辛苦UP。期待新版本！！！

**Comment by ggchivalrous** [comment]
@erbiaoger 是我误判了，是相机信息过滤那里漏了些空判断，导致异常了
