### ISSUE TITLE
输出的图片会多一块白色的颜色块

### ISSUE THREAD

**Issue by itgoyo** [ggchivalrous/yiyin#2]
相机图片加水印效果挺好的

![DSC00530](https://github.com/ggchivalrous/yiyin/assets/23348551/265673dd-b2a7-4044-853e-0dc0e631d60f)

有个问题就是如果不是初始相片文件，类似这张图我是微信发过来然后转存的，生成的水印图片边框是挺好看的，但是就是会多出一块顶部的白边，图片的原始尺寸3840 × 2160，请问这个有办法解决么？大佬

![2481699809686](https://github.com/ggchivalrous/yiyin/assets/23348551/ae138a16-98d6-4239-89d0-727463d95a42)

![2481699809686_ pic_hd](https://github.com/ggchivalrous/yiyin/assets/23348551/1d8ba4c8-0fdf-4f48-838e-d3d9407bc3b0)

**Comment by itgoyo** [comment]
抱歉没问题了，我刚刚不知道点的哪里下载的1.1.0版本，后面看了readme之后发现样式不一样，然后看到了1.1.2的版本，用1.1.2版本已经正常，感谢大佬优质的开源项目

**Comment by ggchivalrous** [comment]
这个是因为没有识别出相机信息的问题，最新版做了处理
