### ISSUE TITLE
是否有计划适配移动端？

### ISSUE THREAD

**Issue by liyiheng** [ggchivalrous/yiyin#22]

**Comment by ggchivalrous** [comment]
我所接触的知识里面，手机端没有任何可以平替的功能来实现我现有的现有的功能。所以我做不到_(:з」∠)_

**Comment by liyiheng** [comment]
好吧，还以为 electron 可以直接打包成手机 app
Linux 包好打么，有 Linux包就能用现成的了😃

我在尝试用 flutter 做一个 demo， 在 rust 中实现图片处理程序供 dart 调用，目前只能给图片加上模糊的背景，也没用上严谨的阴影算法；
然后发现 flutter 原生控件也能实现图片高斯模糊、圆角、阴影这类效果并且可以将控件截成图片，甚至性能更好。
但是没有前端经验，flutter 也是现用现查，迟迟未能详细对比 rust+dart 和纯 dart 两种实现 。

另外，测试过程中发现深色图片跟背景容易溶到一块，看不出明显界限，从 README 例子看 yiyin 似乎也有这个问题，也许提高背景亮度可以缓解，还没验证效果

**Comment by ggchivalrous** [comment]
只要能找到对应的api就能实现这里的所有功能，我这个不是electron的问题，而是用了ffmpeg和一些node的模块，在移动端就没法用。至于你说的那个背景过暗问题现阶段有做亮度分析然后加一层灰色背景，不过效果似乎不是很理想

**Comment by ggchivalrous** [comment]
然后flutter 实现的模糊圆角等效果，如果不能按原画质输出，那么也是没用，如果可以接受截图输出，那么前端h5就能做到这些

**Comment by ggchivalrous** [comment]
你说的Linux包是什么，我可以打出Linux系统的程序只是觉得没什么人会用就没打包

**Comment by liyiheng** [comment]
> 你说的Linux包是什么，我可以打出Linux系统的程序只是觉得没什么人会用就没打包

appimage 格式的应该比较通用，而且没啥依赖问题，只是包有点大

**Comment by liyiheng** [comment]
> 然后flutter 实现的模糊圆角等效果，如果不能按原画质输出，那么也是没用，如果可以接受截图输出，那么前端h5就能做到这些

确实，最多保证尺寸，画质没法控制了

**Comment by ggchivalrous** [comment]
> > 你说的Linux包是什么，我可以打出Linux系统的程序只是觉得没什么人会用就没打包
> 
> 
> 
> appimage 格式的应该比较通用，而且没啥依赖问题，只是包有点大

Appimage好像没见过，我看到的有deb 格式的

**Comment by liyiheng** [comment]
> > > 你说的Linux包是什么，我可以打出Linux系统的程序只是觉得没什么人会用就没打包
> > 
> > 
> > 
> > appimage 格式的应该比较通用，而且没啥依赖问题，只是包有点大
> 
> Appimage好像没见过，我看到的有deb 格式的

我周末研究一下

**Comment by ggchivalrous** [comment]
> > > > 你说的Linux包是什么，我可以打出Linux系统的程序只是觉得没什么人会用就没打包
> > > 
> > > 
> > > appimage 格式的应该比较通用，而且没啥依赖问题，只是包有点大
> > 
> > 
> > Appimage好像没见过，我看到的有deb 格式的
> 
> 我周末研究一下

<img width="315" alt="image" src="https://github.com/ggchivalrous/yiyin/assets/76425888/c2331412-c028-4c44-ae49-d713abc0c14e">
只有这两种格式，不知道你要的那个是哪个，感兴趣也可以自己搜搜如何构建

**Comment by Hanwn** [comment]
可以看下我的项目 https://github.com/Hanwn/PhotosMark，利用浏览器跨平台，可以在web中访问，
在线访问地址： https://photosmark.art
