### ISSUE TITLE
取消勾选原宽高输出后，竖图生成方向错乱。

### ISSUE THREAD

**Issue by hackzx** [ggchivalrous/yiyin#24]
# 勾选原宽高输出
![_Z303656](https://github.com/ggchivalrous/yiyin/assets/5981317/a2fc2469-f945-4b05-9e4f-a7fec50f2856)

# 未勾选原高宽输出
![_Z303656-1](https://github.com/ggchivalrous/yiyin/assets/5981317/a9cf91db-2826-4930-bcb5-92915569d78c)

**Comment by ggchivalrous** [comment]
什么版本出现的这个问题，麻烦把软件界面截图发出来看一下

**Comment by hackzx** [comment]
版本号是 v1.3.6
软件截图为
![图片](https://github.com/ggchivalrous/yiyin/assets/5981317/aac45b1a-1e3a-4ad3-a5b3-35b72714cca3)
并附上测试用图：
[测试图片.zip](https://github.com/ggchivalrous/yiyin/files/13702725/default.zip)

**Comment by ggchivalrous** [comment]
嗯，确实是有问题，看来有bug，我下个版本修复一下，只能麻烦你将就一下(/ω＼)

**Comment by hackzx** [comment]
哈哈哈哈行，辛苦了🫣
