### ISSUE TITLE
【功能建议】建议增加纯色背景颜色选择功能

### ISSUE THREAD

**Issue by WYY-cj** [ggchivalrous/yiyin#27]
当前纯色背景默认使用白色，可考虑提供颜色选择（先识别图片中色值，提取所占比例较高的三种颜色以供选择）
-考虑到图片整体的一致性及和谐行，此方法大概率会产生较好效果，供大佬参考！

**Comment by ggchivalrous** [comment]
可以考虑，但要往后一两个版本

**Comment by ggchivalrous** [comment]
1.5.4已经添加颜色选择，主题色后续可能支持，先这样
