### ISSUE TITLE
【功能建议】建议增加相机品牌logo的功能

### ISSUE THREAD

**Issue by zilun-wang** [ggchivalrous/yiyin#28]
感谢作者制作了这个工具 非常实用！

希望可以增加一个选项可以根据机型显示品牌logo 某些品牌用logo相比用文字可能更加美观一些
效果大概如下图所示：
![IMG_3540](https://github.com/ggchivalrous/yiyin/assets/52902514/e2024db3-4848-4ad4-bdc8-19c2bf0fa707)

**Comment by ggchivalrous** [comment]
有，在下一个版本

**Comment by ggchivalrous** [comment]
是的，在1.4版本，如果你懂一点技术的话，可以拉1.4的功能分支尝试一下，有一个自定义参数
你只要上传logo图片就行，具体效果如图
![DSC_4499-2](https://github.com/ggchivalrous/yiyin/assets/76425888/90a83ba7-dd6d-4542-87c6-f6f987e7caae)

**Comment by ggchivalrous** [comment]
你需要以下步骤：
1. 拉去仓库代码，切换到1.4功能分支
2. 在项目目录运行 npm install
3. npm run start看看是否可以正常启动
4. npm run package打包即可

**Comment by ggchivalrous** [comment]
这个mergeDefOpt 函数有个参数是undefined 没做处理，在mask/index.svelte 文件里，你可以先加个判断，target参数为空则返回cpDef

**Comment by ggchivalrous** [comment]
https://github.com/ggchivalrous/yiyin/issues/5
你用这个看看？还是小的话可以调那个大小

**Comment by ggchivalrous** [comment]
Svg 这个我研究研究，至于你build出来白屏，可能跟我改了项目的环境变量有关，我还没完整测试过。所以不确保能顺利使用

**Comment by Arrebol2020** [comment]
> 你需要以下步骤：
> 
> 1. 拉去仓库代码，切换到1.4功能分支
> 2. 在项目目录运行 npm install
> 3. npm run start看看是否可以正常启动
> 4. npm run package打包即可

为什么我使用npm install 出现下面的错误
![Uploading image.png…]()

**Comment by ggchivalrous** [comment]
> > 你需要以下步骤：
> 
> > 
> 
> > 1. 拉去仓库代码，切换到1.4功能分支
> 
> > 2. 在项目目录运行 npm install
> 
> > 3. npm run start看看是否可以正常启动
> 
> > 4. npm run package打包即可
> 
> 
> 
> 您好，为什么我使用npm install 出现下面的错误
> 
> PS E:\Codes\yiyin> npm install
> 
> npm ERR! code 1
> 
> npm ERR! path E:\Codes\yiyin\node_modules\electron
> 
> npm ERR! command failed
> 
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
> 
> npm ERR! RequestError: read ECONNRESET
> 
> npm ERR!     at ClientRequest.<anonymous> (E:\Codes\yiyin\node_modules\got\dist\source\core\index.js:970:111)
> 
> npm ERR!     at Object.onceWrapper (node:events:629:26)
> 
> npm ERR!     at ClientRequest.emit (node:events:526:35)
> 
> npm ERR!     at origin.emit (E:\Codes\yiyin\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
> 
> npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:495:9)
> 
> npm ERR!     at TLSSocket.emit (node:events:514:28)
> 
> npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
> 
> npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
> 
> npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 
> npm ERR!     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
> 
> 
> 
> npm ERR! A complete log of this run can be found in: C:\Users\zc\AppData\Local\npm-cache\_logs\2024-01-09T03_24_47_500Z-debug-0.log

网络问题，你可以切换成国内源试试？

**Comment by Arrebol2020** [comment]
> > > 你需要以下步骤：
> > 
> > 
> > > 
> > 
> > 
> > > 1. 拉去仓库代码，切换到1.4功能分支
> > 
> > 
> > > 2. 在项目目录运行 npm install
> > 
> > 
> > > 3. npm run start看看是否可以正常启动
> > 
> > 
> > > 4. npm run package打包即可
> > 
> > 
> > 您好，为什么我使用npm install 出现下面的错误
> > PS E:\Codes\yiyin> npm install
> > npm ERR! code 1
> > npm ERR! path E:\Codes\yiyin\node_modules\electron
> > npm ERR! command failed
> > npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
> > npm ERR! RequestError: read ECONNRESET
> > npm ERR!     at ClientRequest. (E:\Codes\yiyin\node_modules\got\dist\source\core\index.js:970:111)
> > npm ERR!     at Object.onceWrapper (node:events:629:26)
> > npm ERR!     at ClientRequest.emit (node:events:526:35)
> > npm ERR!     at origin.emit (E:\Codes\yiyin\node_modules@szmarczak\http-timer\dist\source\index.js:43:20)
> > npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:495:9)
> > npm ERR!     at TLSSocket.emit (node:events:514:28)
> > npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
> > npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
> > npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> > npm ERR!     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
> > npm ERR! A complete log of this run can be found in: C:\Users\zc\AppData\Local\npm-cache_logs\2024-01-09T03_24_47_500Z-debug-0.log
> 
> 网络问题，你可以切换成国内源试试？

换源解决了，但我添加新字体并使用后，生成的图像还是以默认的字体显示，并未更新。这是我操作的问题吗

**Comment by ggchivalrous** [comment]
字体这个我测过是可以的，是不是字体不明显？找个很奇怪的字体试试？字体记得包含英文字符

**Comment by Arrebol2020** [comment]
嗯嗯好，我再试试，哥，你回复的真的好快

**Comment by ggchivalrous** [comment]
_(:з」∠)_上班看看就回了
