### ISSUE TITLE
关于新版本的一点建议

### ISSUE THREAD

**Issue by Lawrenceeeeeeeeee** [ggchivalrous/yiyin#3]
![image](https://github.com/ggchivalrous/yiyin/assets/76642508/2a8bf736-b721-499b-8a09-3556a07c7bcd)
如上，每次登录进去都需要手动设置一个值，比较麻烦。如果默认一个背景比例（如16：9），然后有需要其他比例的用户可以自己修改并长期保存（下一次登录不变直到重新修改），这样会不会更好。不过新版本的功能很不错，至少能够满足了，致谢楼主！

**Comment by ggchivalrous** [comment]
我找个时间优化一下代码，随便加上
