### ISSUE TITLE
是否有开发手机端app的计划

### ISSUE THREAD

**Issue by yizyelu** [ggchivalrous/yiyin#35]
是否已经新建文件夹📁了呢？🤨🤨🤨 希望能上架app store！！！！！付费也支持作者！！！

**Comment by ggchivalrous** [comment]
本人没有移动端开发经验，然后就是桌面端使用的技术似乎不能在移动端使用，所以这个没法做，除非使用存网页上传图片来制作。但这需要服务器支持。如果你有自己的服务器，我可以帮你转成H5等形式自行部署使用

**Comment by ggchivalrous** [comment]
h5就是使用浏览器访问现在的水印页面，然后使用浏览器生成边框，但实际原理是将图片上传到服务器，因为某些模块只在服务器上可以使用

**Comment by fierceX** [comment]
@ggchivalrous 我认为自部署也是有需求的，可以考虑出个自部署的版本出来

**Comment by ggchivalrous** [comment]
> @ggchivalrous 我认为自部署也是有需求的，可以考虑出个自部署的版本出来

目前暂时没有精力去弄自部署版本
