### ISSUE TITLE
增加手机品牌Logo及无人机品牌Logo

### ISSUE THREAD

**Issue by yizyelu** [ggchivalrous/yiyin#36]
是不是可以增加相机品牌logo商店，使用者可以根据需求进行在logo商店里进行下载使用？

**Comment by ggchivalrous** [comment]
最新版我有内置很多的相机品牌logo，可以自己选择使用。都是经过我手动调整过的。无人机和手机这块的话，后续慢慢加，毕竟品牌还是很多的。然后你说的下载是想把logo下载到你本地嘛？
