### ISSUE TITLE
关于尼康机器的一点建议

### ISSUE THREAD

**Issue by lonelyman0108** [ggchivalrous/yiyin#4]
尼康Z72机器的exif信息中的机型是Z7_2 再这样显示有点丑 希望能在识别到时替换为 Z7 II，Z62也会有这种问题

**Comment by ggchivalrous** [comment]
嗯我没有这些机型的原图，所以只能见一个适配一个，我后面加上

**Comment by ggchivalrous** [comment]
新版本应该是做了适配，我没有这些机型的原片所以具体效果看最新版反馈
