### ISSUE TITLE
【功能建议】增加拖动图片到软件界面快速添加图片和快速生成功能

### ISSUE THREAD

**Issue by moxuec** [ggchivalrous/yiyin#41]
能否增加下面两个功能
1、拖动文件夹的一张或多张图片到软件，可以快速添加的功能。
2、增加一个快速生成开关，图片拖进去之后无需手动点击生成“生成印框”按钮，就可以快速输出。

**Comment by ggchivalrous** [comment]
这建议不错，我记一下
