### ISSUE TITLE
【功能建议】也给png等格式加上参数

### ISSUE THREAD

**Issue by traveler5258** [ggchivalrous/yiyin#46]
现在貌似只能给jpg格式加上参数，png只能加框框，大佬往后有意愿更新一下这个功能吗

**Comment by LJJbyZJU** [comment]
附议，文件格式可以再多一些。可以先实现印框的多格式支持。

**Comment by ggchivalrous** [comment]
> 附议，文件格式可以再多一些。可以先实现印框的多格式支持。

Png格式图片最新版会支持，最新版用了exiftool工具，理论上他支持的就是我能支持的，输出的图片最终只能转成jpg，png输出会出现图片大小翻倍的情况

**Comment by ggchivalrous** [comment]
1.5已支持
