### ISSUE TITLE
跪求大佬增加富士型号！

### ISSUE THREAD

**Issue by ryanundorgel** [ggchivalrous/yiyin#5]
软件不识别相机的机型 只显示型号
求大佬增加富士xs10的机型标识!! 很喜欢你的这个软件！
https://github.com/ryanundorgel/SAVE/commit/61fcec7d4d3ef187418140bd00fc8aca582522c3
我在自己的项目里上传了富士的logo矢量图和XS10的机型logo矢量图,如果有需要请您自取呀!
可以增加的话，真的非常感谢!!
![微信截图_20231120224543](https://github.com/ggchivalrous/yiyin/assets/80960880/55c31314-7cb6-4fa7-b5f3-bd4f866e6913)
![微信截图_20231120224408](https://github.com/ggchivalrous/yiyin/assets/80960880/de8429de-592d-469d-aef6-50ccc1a478b5)

**Comment by ggchivalrous** [comment]
嗯，后面会收集各个机型数据适配，现在正在弄了
