### ISSUE TITLE
Request for Adding Custom Font Feature

### ISSUE THREAD

**Issue by liftes** [ggchivalrous/yiyin#6]
Hello Yiyin Team,

First off, I want to extend my compliments to the developers and contributors for creating such a robust and user-friendly software. It's evident that a lot of thought and expertise has been invested in its development, and it shows in the quality of the application.

As someone who is not deeply versed in front-end languages, I've encountered some challenges in tailoring the application to my specific needs. One feature that I believe would significantly enhance user experience is the ability to customize the parameter fonts through a user interface.

Currently, it seems that there is no straightforward way for users to modify the font settings for parameters without diving into the code. An interface that allows for this kind of customization would be greatly beneficial, especially for those who may not have the technical background to modify the frontend code directly.

If this feature aligns with the vision for the software and is feasible for the development roadmap, I and likely many others in the community would greatly appreciate its implementation.

Thank you for considering this request, and for your ongoing efforts to improve yiyin.

Best regards,
Norfe

**Comment by ggchivalrous** [comment]
Well, I am also aware of the shortcomings in interaction. Currently, the software is being improved, and the next version will support some user-defined functions

**Comment by ggchivalrous** [comment]
My English proficiency may not be that high, and if my response seems strange, I am deeply sorry

**Comment by liftes** [comment]
在机型适配上，可以将索尼的ILCE-进行替换，如使用：
`exifInfo.Model = exifInfo.Model.replace('ILCE-', 'SONY α');`

另外，对应深色背景的图片，可以考虑先计算当前图片的平均亮度，然后对背景进行一个灰色遮罩，而不是黑色，这样可以在生成图片后保留较好的图形轮廓。如：
  function getAverageBrightness(ctx, width, height) {
  const imageData = ctx.getImageData(0, 0, width, height);
  const data = imageData.data;
  let totalBrightness = 0;

  for (let i = 0; i < data.length; i += 4) {
    // 简单的亮度计算方法
    const brightness = (data[i] + data[i + 1] + data[i + 2]) / 3;
    totalBrightness += brightness;
  }

之前的代码：
    // ctx.fillStyle = 'rgba(0, 0, 0, 0.2)';
    // ctx.fillRect(0, 0, _canvas.width, _canvas.height);
    // ctx.fillStyle = 'black';
    替换为：
  return totalBrightness / (width * height);
  }
  
      const averageBrightness = getAverageBrightness(ctx, _canvas.width, _canvas.height);
    console.log(averageBrightness)

    if (averageBrightness < 40) {
    ctx.fillStyle = 'rgba(128, 128, 128, 0.5)'; // 灰色半透明覆盖层
    ctx.fillRect(0, 0, _canvas.width, _canvas.height);
    } else if (option.background) {
      ctx.fillStyle = option.background;
      ctx.fillRect(0, 0, _canvas.width, _canvas.height);
    }
    ctx.fillStyle = 'black';

        
      我成功测试了上述代码，但好像打包为exe过程存在一些问题。

**Comment by ggchivalrous** [comment]
@liftes 感谢你的代码，我会加上这个处理，然后索尼的exif内容没有 `SONY α` 吗

**Comment by liftes** [comment]
我检查了a9的照片和a7rm4的照片，其记录的都是ILCE-9 和 ILCE-7rm4。而大写的I和小写的l很难区分。

**Comment by ggchivalrous** [comment]
你是看输出的型号吗，还是直接看的exif模块输出的内容？如果可以，有原图给我试一下吗

**Comment by ggchivalrous** [comment]
嗯，我看看，期待你的邮件

**Comment by liftes** [comment]
我压缩了一下图片，github邮箱好像有大小限制。


liftes
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ggchivalrous/yiyin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月23日(星期四) 晚上11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ggchivalrous/yiyin] Request for Adding Custom Font Feature (Issue #6)





 
嗯，我看看，期待你的邮件

**Comment by ggchivalrous** [comment]
我有公开的私人邮箱，你可以发个附件过来

**Comment by liftes** [comment]
![_A9_8164-Pano-1](https://github.com/ggchivalrous/yiyin/assets/69229029/79cefbc5-bd2b-45f0-8b88-b015703d162f)
![_A730685](https://github.com/ggchivalrous/yiyin/assets/69229029/4af79aa1-c68e-4ddf-a836-c9bb45f683f0)
![_DSC7314_1](https://github.com/ggchivalrous/yiyin/assets/69229029/6efc7057-9a2f-4d04-9c9f-84d956cd1e0c)
![中国尊月升](https://github.com/ggchivalrous/yiyin/assets/69229029/892c42d3-9afa-46e3-98cc-c74651ba96e3)

**Comment by ggchivalrous** [comment]
我看了系统显示的信息，可以知道是索尼厂商，但是 α 这个符号好像很特殊

**Comment by liftes** [comment]
是，索尼在机身的都标注的是斜体的α

**Comment by ggchivalrous** [comment]
看来是要做一层映射才能更好的显示
