### ISSUE TITLE
希望大佬能添加手动修改机型的功能

### ISSUE THREAD

**Issue by DogCheck** [ggchivalrous/yiyin#7]
我是松下的相机，自动获取的机型有点鬼畜，希望可以增加一个手动修改参数或是添加文字的功能
emmmm...然后就是不知道咋滴突然间就用不了，选择照片后输出文件夹没有任何反应。卸载重启了也没办法:(

**Comment by ggchivalrous** [comment]
突然输出不了可能是照片信息获取那里有问题，还有就是同名覆盖。你说的这个机型问题是我没有做适配，这个功能正在加，然后修改信息功能也会一并加上
