### ISSUE TITLE
希望支持位置可变的自定义文本框以及更多参数~

### ISSUE THREAD

**Issue by ChenYun4164** [ggchivalrous/yiyin#80]
up主大大，工具很好用，投币感谢！自己后面也会向周围的摄影爱好者推荐这款工具
不过仍能希望能支持位置可变的自定义文本框以及一些参数，更丰富工具的灵活性

某些时候，更想要记录或讲述一下照片背后的故事，例如这样
![image](https://github.com/ggchivalrous/yiyin/assets/45526365/ee488afa-fe1d-4bd4-aff4-2a472d2fa931)

使用了这个工具后发现
1. 不支持调整文本框位置，虽然可以自定义文本模板，但好像不支持调整位置
期望可以根据照片宽度选择左下或右下位置
2. 不支持”照相机制造商“参数，有的时候只想展示下照相机制造商，不想展示具体型号（一个是为了简洁，另一个是有的手机在拍摄时记录的型号不是大家熟悉的型号）🙂
如上图右下角的Shot by Xiaomi
比如这个，其实是Xiaomi 11 Ultra 拍摄的
![image](https://github.com/ggchivalrous/yiyin/assets/45526365/e6ea0693-039a-4080-bf08-e7c1773a201b)

3. 能否增加一个新参数，是拍摄日期的裁剪，只显示年月日，不展示具体的时分秒（一个是为了简洁，另一个是有时经过后期软件处理后会被覆盖，而手动修改该字段只能修改年月日）
![image](https://github.com/ggchivalrous/yiyin/assets/45526365/a6a70693-406c-4a3b-a33e-70dfd02829b1)

**Comment by ggchivalrous** [comment]
第一点在1.6会有，但短期内不会弄出来，是一个大改动需要长周期。第二点可以选择是否显示某些参数来实现。第三点这个后面会考虑加指定日期模板而不是新参数
