### ISSUE TITLE
希望能增加用户自行添加/替换Logo的功能

### ISSUE THREAD

**Issue by ziruifu** [ggchivalrous/yiyin#84]
在尝试导入理光GRIIIx拍摄的照片时相机logo处会显示全称“Ricoh imaging company, ltd. ricoh gr iiix”而非理光logo+相机型号。考虑到相机品牌型号种类繁多，如果开发者自己无法添加所有logo的话，不如开放功能交给用户自行添加，比如把透明背景logo文件放在logo文件夹下之类的情况（我记得也是某个开源水印软件具备的功能）

**Comment by ggchivalrous** [comment]
软件支持自定义，理光不会这样显示吧我记得

**Comment by ziruifu** [comment]
确实，在根目录/resources/app/web/logo找到了理光的logo文件，但是不知为何没有调用。样张附在本comment下，不知道能不能帮助找到问题
[RICOH.zip](https://github.com/user-attachments/files/15603349/RICOH.zip)

**Comment by ggchivalrous** [comment]
请在软件里面上传

**Comment by ggchivalrous** [comment]
并在参数设置里面自定义使用

**Comment by ziruifu** [comment]
> 请在软件里面上传

压缩包里是我使用的照片样张，不是logo样张。我觉得出问题的照片样张或许能为你debug提供帮助，能理解您不愿意下载未经验证的压缩包，但是github issue只允许上传10MB内文件。

> 并在参数设置里面自定义使用

我在logo文件夹下发现了您预留的logo文件，生成的边框文本我也认为是成功抓取了metadata，推测只是没能调用logo，不太明白您是要我再找个logo文件然后直接硬添加到边框中吗？

**Comment by ggchivalrous** [comment]
软件读取到的内容就是 Ricoh imaging company ，而我开发里面默认是认为只有ricoh 并用这个词去匹配logo ，目前你只能自定义，也就是在参数设置里面，选择内置的理光logo，强制替换。

**Comment by ggchivalrous** [comment]
如果对logo不满意需要自定义别的logo样式，你可以点上传图片到软件里面，软件会用你设置的图片去替换这个logo

**Comment by ggchivalrous** [comment]
如果还有什么不懂，我有开通 壹印 公众号，你可以在里面看参数，模板等的使用方法

**Comment by ziruifu** [comment]
了解，多谢指导！
