### ISSUE TITLE
你好，请问有计划将关键的转换方法，编写成api接口么？

### ISSUE THREAD

**Issue by kuschzzp** [ggchivalrous/yiyin#92]
你好，这个软件功能确实很好用。但是没有手机端，确实不太方便，如果开放接口的话，部署上服务器，就可以通过编写 快捷指令 的方式在手机上使用了。

**Comment by ggchivalrous** [comment]
这个项目准备不更新了，会维护修bug，所以想要的话你可以自己转一下

**Comment by ggchivalrous** [comment]
如果你在等移动端的话，这个月估计会上苹果应用商店，如果是想自己搭服务器处理那就改一下electron接口部分的就可以
