### ISSUE TITLE
请求添加 leica cl的logo支持

### ISSUE THREAD

**Issue by psernokx** [ggchivalrous/yiyin#94]
![image](https://github.com/user-attachments/assets/47a26045-a330-4b60-a926-3b909ef66963)
{
  "Make": "LEICA CAMERA AG",
  "Model": "LEICA CL",
  "LensMake": "N/A",
  "LensModel": "N/A",
  "FNumber": "0",
  "ISO": "6400",
  "FocalLength": "0",
  "FocalLengthIn35mmFormat": "0",
  "ExposureTime": "1/400",
  "DateTimeOriginal": "2024/09/22 09:53:05",
  "ExposureCompensation": "+0.6",
  "WhiteBalance": "Auto",
  "ExposureProgram": "M",
  "MeteringMode": "评价测光"
}

**Comment by ggchivalrous** [comment]
软件支持自定义，可以先强制替换成内置的莱卡LOgo
