### ISSUE TITLE
[Feature] 在修改参数后重置生成状态为未完成

### ISSUE THREAD

**Issue by Adamska1008** [ggchivalrous/yiyin#96]
## 问题描述

在当前的实现中，当我输出一张印框照片后，该照片的状态会被标记为“已完成”。即使我更改了参数或修改了字体，只要不更换照片，再次点击生成印框后将没有任何响应。这种设计可能会影响多次生成以对比不同参数效果的便利性。

## 功能描述

可能的解决策略：
1. 当用户修改任意一个参数时，重置照片状态为“未完成”，这样用户可以在不更换照片的情况下重新点击生成印框。
2. 直接忽略照片状态，只要用户点击了生成印框，就重新生成照片。

大家对此问题有什么看法？

**Comment by ggchivalrous** [comment]
处理完的图片不允许二次使用，需要重新放入图片

**Comment by ggchivalrous** [comment]
图片是累加进去的，如果按照你的要求，处理完需要用户手动清空，一样对部分人不友好
